name: retainless-collector-cicd

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - name: Install and Compile
        run: |
          corepack enable pnpm
          pnpm install
          pushd packages/log-processor && pnpm run build && popd
          pushd packages/cli && pnpm run build && popd
      - name: Package
        run: |
          pushd packages/log-processor && pnpm pack && popd
          pushd packages/cli && pnpm pack && popd
      - uses: actions/upload-artifact@v4
        with:
          name: retainless-collector-packages
          path: '**/retainless-*.tgz'
          if-no-files-found: error
      - uses: actions/upload-artifact@v4
        with:
          name: retainless-collector-bundles
          path: 'packages/log-processor/build/bundles/*.zip'
          if-no-files-found: error
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'
    environment: release
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          sparse-checkout: |
            package.json
      - uses: actions/download-artifact@v5
        with:
          path: build
          pattern: retainless-collector-*
          merge-multiple: true
      - uses: actions/setup-node@v6
        with:
          node-version: '22.x'
      - name: Deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          export tag=v$(cat package.json | jq -r '.version')
          
          echo "//npm.pkg.github.com/:_authToken=$GITHUB_TOKEN" >> ~/.npmrc
          echo '@retainless:registry=https://npm.pkg.github.com' >> ~/.npmrc
          
          export IS_PRERELEASE=$(case "$tag" in *rc*) printf 'true';; esac)
          
          gh release create "$tag" \
              "build/*.zip" \
              --repo="$GITHUB_REPOSITORY" \
              --title="$tag" \
              ${IS_PRERELEASE:+"--prerelease"} \
              --generate-notes
          
          pushd build/packages/cli && npm publish \
            ${IS_PRERELEASE:+"--tag next"} \
            "retainless-cli-${tag#v}.tgz" && popd
          pushd build/packages/log-processor && npm publish \
            ${IS_PRERELEASE:+"--tag next"} \
            "retainless-log-processor-${tag#v}.tgz" && popd
